import{a as u,A as m,S as p,i as f}from"./assets/vendor-b090611b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=i(t);fetch(t.href,n)}})();const g=document.querySelector(".open-menu-btn"),w=document.querySelectorAll(".header-menu-item"),y=document.querySelector(".header-menu-list");g.addEventListener("click",l);w.forEach(e=>{e.addEventListener("click",l)});function l(){y.classList.toggle("slide")}const h="https://portfolio-js.b.goit.study/api/reviews";async function L(){const{data:e}=await u.get(`${h}`,{headers:{Accept:"application/json"},method:"Get"});return e}document.addEventListener("DOMContentLoaded",function(){const e=Array.from(document.querySelectorAll(".accordion-container"));new m(e,{duration:400,openOnInit:"all",showMultiple:!0,onOpen:function(o){o.querySelector("use[href]").setAttribute("href","../img/icons.svg#icon-arrow-up")},onClose:function(o){o.querySelector("use[href]").setAttribute("href","../img/icons.svg#icon-arrow-down")}})});const r=new p(".swiper",{navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},slidesPerView:1,on:{slideChange:function(){r.isEnd?r.navigation.nextEl.classList.add("swiper-button-disabled"):r.navigation.nextEl.classList.remove("swiper-button-disabled"),r.isBeginning?r.navigation.prevEl.classList.add("swiper-button-disabled"):r.navigation.prevEl.classList.remove("swiper-button-disabled")}}});console.log(r);document.getElementById("animation");function v(e){let o=e.getBoundingClientRect();return o.top>=0&&o.bottom<=window.innerHeight||o.bottom>=0&&o.top<=window.innerHeight}function d(){let e=document.querySelector(".marquee");v(e)?e.querySelectorAll(".marquee__line").forEach(function(i){i.classList.add("animate-covers")}):e.querySelectorAll(".marquee__line").forEach(function(i){i.classList.remove("animate-covers")})}document.addEventListener("DOMContentLoaded",d);window.addEventListener("scroll",d);const b=document.querySelector(".swiper-wrapper"),q=document.querySelector(".placeholder_text");async function E(){try{const e=await L();b.insertAdjacentHTML("beforeend",S(e))}catch{q.classList.replace("visually-hidden","title_not_found"),f.show({message:"Reviews Not found",backgroundColor:"#ed3b44",messageColor:"#fafafa",position:"topRight",timeout:2e3})}}function S(e){return e.map(({id:o,author:i,avatar_url:s,review:t})=>`
    <div class="swiper-slide">
    <li class="card" data-id ="${o}">
    <img class="card_img" src="${s}" alt="photo">
    <h3 class="card_title">${i}</h3>
    <p class="card_text">${t}</p> 
    </li>
    </div>
    `).join("")}E();const A=document.querySelector(".open-modal-btn"),M=document.querySelector(".close-modal-btn"),O=document.querySelectorAll(".modal-item-link"),C=document.querySelector(".modal-window-cont");A.addEventListener("click",a);M.addEventListener("click",a);O.forEach(e=>{e.addEventListener("click",a)});function a(){C.classList.toggle("is-open"),document.body.classList.toggle("menu-is-open")}
//# sourceMappingURL=commonHelpers.js.map
